'use server';

/**
 * @fileOverview This file defines a Genkit flow for generating conversation starters based on a given topic.
 *
 * The flow takes a topic as input and returns a generated conversation starter.
 * The file exports: GenerateConversationStarterInput, GenerateConversationStarterOutput, generateConversationStarter
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateConversationStarterInputSchema = z.object({
  topic: z.string().describe('The topic for which to generate a conversation starter.'),
});
export type GenerateConversationStarterInput = z.infer<typeof GenerateConversationStarterInputSchema>;

const GenerateConversationStarterOutputSchema = z.object({
  conversationStarter: z.string().describe('A conversation starter generated by the AI.'),
});
export type GenerateConversationStarterOutput = z.infer<typeof GenerateConversationStarterOutputSchema>;

const generateConversationStarterPrompt = ai.definePrompt({
  name: 'generateConversationStarterPrompt',
  input: {schema: GenerateConversationStarterInputSchema},
  output: {schema: GenerateConversationStarterOutputSchema},
  prompt: `You are an AI assistant designed to generate creative and engaging conversation starters.

  Based on the topic provided, create a single, short question that can be used to start a conversation.

  Topic: {{{topic}}}

  Conversation Starter:`,
});

const generateConversationStarterFlow = ai.defineFlow(
  {
    name: 'generateConversationStarterFlow',
    inputSchema: GenerateConversationStarterInputSchema,
    outputSchema: GenerateConversationStarterOutputSchema,
  },
  async input => {
    const {output} = await generateConversationStarterPrompt(input);
    return output!;
  }
);

export async function generateConversationStarter(
  input: GenerateConversationStarterInput
): Promise<GenerateConversationStarterOutput> {
  return generateConversationStarterFlow(input);
}
